namespace ScriptsOfTribute;

/// <summary>
/// Ini the beninging (https://www.youtube.com/watch?v=fWKB8zdVM-U) we only creates chance nodes for direct card effects that lead to random effects, while ignoring Random Action Combo Effect 
/// because of the complexity. We want to first establish that the chance nodes actually provide improvements
/// </summary>
public enum CardId
{
    CURRENCY_EXCHANGE = 0,
    LUXURY_EXPORTS = 1,// Obvious action play
    OATHMAN = 2,
    EBONY_MINE = 3,
    HLAALU_COUNCILOR = 4,
    HLAALU_KINSMAN = 5,
    HOUSE_EMBASSY = 6,
    HOUSE_MARKETPLACE = 7,
    KWAMA_EGG_MINE = 8,
    HIRELING = 9,
    HOSTILE_TAKEOVER = 10,
    CUSTOMS_SEIZURE = 11,
    GOODS_SHIPMENT = 12,// Obvious action play
    MIDNIGHT_RAID = 13,// Obvious action play
    BLOOD_SACRIFICE = 14,// Random Contract Action Combo Effect TODO add
    BLOODY_OFFERING = 15,// Random Contract Action Combo Effect TODO add
    BONFIRE = 16,
    BRIARHEART_RITUAL = 17,
    CLANWITCH = 18,
    ELDER_WITCH = 19,
    HAGRAVEN = 20,
    HAGRAVEN_MATRON = 21,
    IMPERIAL_PLUNDER = 22,
    IMPERIAL_SPOILS = 23,
    KARTH_MANHUNTER = 24,
    WAR_SONG = 25,// Obvious action play
    BLACKFEATHER_KNAVE = 26,// Obvious agent effect. Random Agent Combo Effect TODO add
    PLUNDER = 27,// Obvious action play
    TOLL_OF_FLESH = 28,// Obvious action play. Random Action Combo Effect TODO add
    TOLL_OF_SILVER = 29,// Obvious action play. Random Action Combo Effect TODO add
    MURDER_OF_CROWS = 30,// Obvious action play
    PILFER = 31,// Obvious action play. Random action effect TODO add. Random Action Combo Effect TODO add
    SQUAWKING_ORATORY = 32,// Obvious action play. Random action effect TODO add. Random Action Combo Effect TODO add
    LAW_OF_SOVEREIGN_ROOST = 33,// TODO Remove from obvious action play. Random Contract Action Combo Effect TODO add
    POOL_OF_SHADOW = 34,// Obvious action play
    SCRATCH = 35,// Obvious action play
    BLACKFEATHER_BRIGAND = 36,// Obvious agent effect. Random Agent Combo Effect TODO add
    BLACKFEATHER_KNIGHT = 37,
    PECK = 38,// Obvious action play
    CONQUEST = 39,
    GRAND_ORATORY = 40,
    HIRAS_END = 41,
    HEL_SHIRA_HERALD = 42,
    MARCH_ON_HATTU = 43,
    SHEHAI_SUMMONING = 44,
    WARRIOR_WAVE = 45,
    ANSEI_ASSAULT = 46,
    ANSEIS_VICTORY = 47,
    BATTLE_MEDITATION = 48,
    NO_SHIRA_POET = 49,
    WAY_OF_THE_SWORD = 50,
    PROPHESY = 51,
    SCRYING_GLOBE = 52,
    THE_DREAMING_CAVE = 53, // Random action effect TODO add
    AUGURS_COUNSEL = 54,
    PSIJIC_RELICMASTER = 55,
    SAGE_COUNSEL = 56,
    PRESCIENCE = 57,
    PSIJIC_APPRENTICE = 58,
    CEPORAHS_INSIGHT = 59,
    PSIJICS_INSIGHT = 60,
    TIME_MASTERY = 61,
    MAINLAND_INQUIRIES = 62,// Obvious action play
    RALLY = 63,// Obvious action play. Random Action Combo Effect TODO add
    SIEGE_WEAPON_VOLLEY = 64,// Obvious action play
    THE_ARMORY = 65,// Obvious action play
    BANNERET = 66,// Obvious agent effect
    KNIGHT_COMMANDER = 67,// Obvious agent effect
    REINFORCEMENTS = 68,// Obvious action play
    ARCHERS_VOLLEY = 69,// Obvious action play
    LEGIONS_ARRIVAL = 70,// Obvious action play
    SHIELD_BEARER = 71,// Obvious agent effect
    BANGKORAI_SENTRIES = 72,// Obvious agent effect
    KNIGHTS_OF_SAINT_PELIN = 73,// Obvious agent effect
    THE_PORTCULLIS = 74,// Obvious action play
    FORTIFY = 75,// Obvious action play
    BAG_OF_TRICKS = 76, // Random Contract Action Combo Effect TODO add
    BEWILDERMENT = 77,// Obvious action play
    GRAND_LARCENY = 78,
    JARRING_LULLABY = 79,
    JEERING_SHADOW = 80,// Obvious agent effect
    MOONLIT_ILLUSION = 81,
    POUNCE_AND_PROFIT = 82,
    PROWLING_SHADOW = 83,// Obvious agent effect
    RINGS_GUILE = 84,// Random Contract Action Combo Effect TODO add
    SHADOWS_SLUMBER = 85,
    SLIGHT_OF_HAND = 86,
    STUBBORN_SHADOW = 87,// Obvious agent effect
    SWIPE = 88,// Obvious action play
    TWILIGHT_REVELRY = 89,// Random Action Combo Effect TODO add
    GHOSTSCALE_SEA_SERPENT = 90,// Obvious action play
    KING_ORGNUMS_COMMAND = 91,
    MAORMER_BOARDING_PARTY = 92,// Obvious action play
    MAORMER_CUTTER = 93,
    PYANDONEAN_WAR_FLEET = 94,// Obvious action play
    SEA_ELF_RAID = 95,// Obvious action play
    SEA_RAIDERS_GLORY = 96,
    SEA_SERPENT_COLOSSUS = 97,// Obvious action play
    SERPENTGUARD_RIDER = 98,
    SERPENTPROW_SCHOONER = 99,// Obvious action play
    SNAKESKIN_FREEBOOTER = 100,
    STORM_SHARK_WAVECALLER = 101,
    SUMMERSET_SACKING = 102,// Obvious action play
    AMBUSH = 103,
    BARTERER = 104,
    BLACK_SACRAMENT = 105,
    BLACKMAIL = 106,
    GOLD = 107,// Obvious action play
    HARVEST_SEASON = 108,// Random constract action effect TODO add
    IMPRISONMENT = 109,
    RAGPICKER = 110,
    TITHE = 111,
    WRIT_OF_COIN = 112,// Obvious action play
}
